### PR TITLE
Revert (temporarily) to 1.4.4 to get py37 build

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This is needed for https://github.com/conda-forge/airflow-feedstock/pull/29 and https://github.com/conda-forge/airflow-feedstock/pull/27

I will revert this PR once this version is in.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
License file seems to be missing for this version, but has been added in subsequent versions.

**Comment by xylar** [comment]
@ocefpaf, if you want to create a temporary branch on `conda-forge/pendulum-feedstock` and merge this there, that would be great!  Then, I'll delete the temp branch once I have access.

**Comment by ocefpaf** [comment]
If you are not maintaining v1.4.4 we can merge it here, wait for the package to be uploaded, and then revert the PR (maybe keep you as the maintainer ;-p).

**Comment by xylar** [comment]
Whatever is easiest!

**Pull request merged**
